import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getSortedNotesData } from "../lib/notes"
import Link from 'next/link'

export default function Home({ allNotesData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className="notes">
            <h1>Notes ({allNotesData.length})</h1>
            <ul>
                {allNotesData.map(({ id, date, title }) => (
                    <li key={id}>
                      <Link href={`/note/${id}`}>
                        <div>
                          <small>{id}</small>
                          <br />
                          <strong>{title}</strong>
                          <br /><br />
                          <em>{date}</em>
                        </div>
                      </Link>
                    </li>
                ))}
            </ul>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const allNotesData = getSortedNotesData()

  return {
      props: {
          allNotesData
      }
  }
}